import type { Metadata } from "next";
import { Geist, Geist_Mono, Fustat, Heebo } from "next/font/google";
import {
  // CheckWindowSize,
  Toaster,
} from "@/components";
// import { AuthProvider } from "@/store";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fustat = Fustat({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  display: "swap",
  variable: "--font-fustat",
});
const heebo = Heebo({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  display: "swap",
  variable: "--font-heebo",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fustat.variable} ${heebo.variable} antialiased font-fustat`}
      >
        {/* <AuthProvider>{children}</AuthProvider> */}
        {/* <CheckWindowSize>{children}</CheckWindowSize> */}
        {children}
        <Toaster position='bottom-right' richColors />
      </body>
    </html>
  );
}
