export * from "./nav-bar";
export * from "./hero";
export * from "./features";
export * from "./services";
export * from "./how-it-works";
export * from "./app-download";
export * from "./faq";
export * from "./updates";
export * from "./footer";
